version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: examdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - examdb-data:/var/lib/postgresql/data

volumes:
  examdb-data:

env_file:
  - .env
